from datetime import datetime
from pathlib import Path
import subprocess

def render_latex_pdf(latex_content: str) -> str:
    """
    Render a LaTeX document to PDF using pdflatex (full path specified).

    Args:
        latex_content: The LaTeX document content as a string

    Returns:
        Path to the generated PDF document
    """
    # Full path to pdflatex
    pdflatex_path = r"C:\Users\bonde\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe"

    try:
        # Step 1: Create output directory
        output_dir = Path("output").absolute()
        output_dir.mkdir(exist_ok=True)

        # Step 2: Setup filenames
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_filename = f"paper_{timestamp}.tex"
        tex_file = output_dir / tex_filename
        tex_file.write_text(latex_content, encoding="utf-8")

        # Step 3: Run pdflatex
        result = subprocess.run(
            [pdflatex_path, "-interaction=nonstopmode", tex_filename],
            cwd=output_dir,
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            print("pdflatex compilation failed:")
            print("STDOUT:", result.stdout)
            print("STDERR:", result.stderr)
            raise RuntimeError("pdflatex compilation failed.")

        # Step 4: PDF file has the same base name as .tex
        pdf_file = output_dir / f"paper_{timestamp}.pdf"
        if not pdf_file.exists():
            raise FileNotFoundError("PDF file was not generated by pdflatex.")

        print(f"Successfully generated PDF at {pdf_file}")
        return str(pdf_file)

    except Exception as e:
        print(f"Error rendering LaTeX: {e}")
        raise


